#!/bin/bash

if [[ $1 =~ ^[~\/] ]]
then
  # its already an absolute path
  lein exec -p "$@"
else
  # This is a relative path, so make it absolute,
  # using the current directory as the base.
  lein exec -p "`pwd`/$@"
fi

